config/routes.rb
Rails.application.routes.draw do
  authenticated :user do
    root :to => 'dashboards#home', :as => :authenticated_root
  end

  root :to => redirect('/users/sign_in')

  devise_for :users, :controllers => { :users => 'users', :registrations => 'registrations', :confirmations => 'confirmations', :password_expired => 'password_expired', :omniauth_callbacks => 'users/omniauth_callbacks' }
  devise_scope :user do
    put '/confirm' => 'confirmations#confirm'
  end

  resource :my_account, :controller => :my_account, :only => [:show]  do
    resource :password_expired, :only => [:show, :update], :controller => :password_expired
  end

  resources :applications do
    resources :environments
    resources :deployments do
      resources :deployment_environments, only: [:index, :show, :output] do
        member do
          get :output
        end
        resources :approvals, :only => [:index, :show]
      end
    end
  end

  resources :approval_groups, :only => [:index, :show]
  resources :deployment_templates
  resources :dashboards, :only => [:index, :show, :home] do
    collection do
      get :home
    end
  end

  resources :approvals, :only => [:waiting] do
    collection do
      get :waiting
    end
  end

  namespace :admin do
    match '/' => 'admin#index', via: :get
    resources :approval_groups, :controllers => { :roles => 'admin/approval_groups' }
    resources :audits, only: [:index, :show]
    resources :dashboards, :controllers => { :dashboards => 'admin/dashboards' }, only: [:index]
    resources :deployment_modules, :controllers => { :roles => 'admin/deployment_modules' }, except: [:new, :create] do
      collection do
        get :upload
        post :perform_upload
      end

      member do
        get :upgrade
        patch :perform_upgrade
      end
    end
    resources :mailer_notification_permissions, :controllers => { :mailer_notification_permissions => 'admin/mailer_notification_permissions' }, :only => [:index]
    resources :roles, :controllers => { :roles => 'admin/roles' }, :only => [:index, :show]
    resources :users,  :controllers => { :users => 'admin/users'}
  end

  namespace :api, :defaults => {:format => :html} do
    root :to => 'api#index'

    resources :api, :controller => :api

    scope module: :v1, constraints: ApiConstraints.new(version: 1, default: true), :defaults => {:format => :json} do
      resources :applications, :only => [:index, :show] do
        member do
          put :watch
          delete :unwatch
        end
        resources :deployments, :only => [:index, :show, :deploy, :create, :update] do
          member do
            post :deploy
            put :watch
            delete :unwatch
          end
          resources :deployment_environments, :only => [:deploy, :destroy, :update_schedule, :cancel_schedule] do
            member do
              post :deploy
              delete :destroy
              patch :update_schedule
              delete :cancel_schedule
            end
            resources :approvals, :only => [:index, :show, :approve, :reject] do
              member do
                post :approve
                post :reject
              end
            end
          end
        end
        resources :environments, :only => [:index, :show, :destroy] do
          member do
            post :deploy
            delete :destroy
          end
        end
      end
      resources :audits, only: [:index, :show]
      resources :deployment_templates
      resources :deployment_modules, only: [:index, :show]
      resources :charts, only: [:approvals_per_deployment, :deployments_per_application] do
        collection do
          get :approvals_per_deployment
          get :deployments_per_application
          get :deployments_created_last_x_days
        end
      end
      resources :approvals, :only => [:waiting] do
        collection do
          get :waiting
        end
      end
      resources :users, only: [:index, :show]
    end
  end
end

app/models/approval.rb
class Approval < ActiveRecord::Base
  include PublicActivity::Model
  include Workflow

  audited associated_with: :deployment_environment

  tracked owner: proc {|controller, model| controller.current_user},
          only: [:approve, :reject],
          params: {
              summary: proc {|controller, model| controller.truncate(model.approver_comment, length: 30)}
          }

  belongs_to :user
  belongs_to :approver, class_name: 'User', foreign_key: 'approver_user_id'
  belongs_to :deployment_environment

  has_one :deployment, through: :deployment_environment
  has_one :environment, through: :deployment_environment

  after_commit :send_initial_email, :on => :create

  workflow do
    state :awaiting_approval do
      event :approve,  transitions_to: :approved
      event :reject,  transitions_to: :rejected
    end
    state :approved
    state :rejected
    on_transition do |from, to, triggering_event, *event_args|
      ApprovalMailer.initialize_notification(self, to) unless to == :awaiting_approval
    end
  end

  def approve(user, approver_comment)
    self.approver_user_id = user.id
    self.approver_comment = approver_comment

    self.save

    self.create_activity key: 'approval.approved', owner: user
  end

  def reject(user, approver_comment)
    self.approver_user_id = user.id
    self.approver_comment = approver_comment

    self.save

    self.create_activity key: 'approval.rejected', owner: user
  end

  def can_approve_reject?(user)
    return false unless (self.deployment.application.approvers.include?(user) || user.has_role?(:approval_admin))

    if self.deployment.user == user
      self.deployment.application.allow_self_approval? || user.has_role?(:approval_admin)
    else
      true
    end
  end

  def already_approved_rejected?
    self.approved? || self.rejected?
  end

  def self.approvals_for_user(user)
    user_approvals = []

    Approval.where(workflow_state: 'awaiting_approval').each do |approval|
      user_approvals << approval if approval.can_approve_reject?(user)
    end

    user_approvals
  end

  private
  def send_initial_email
    ApprovalMailer.initialize_notification(self, self.current_state.to_s.to_sym)
  end
end

app/controllers/api/v1/approvals_controller.rb
class API::V1::ApprovalsController < API::BaseController
  load_and_authorize_resource
  before_action :set_approval, except: [:index, :waiting]
  before_action :set_deployment, :except => [:waiting]
  before_action :set_deployment_environment, :except => [:waiting]
  before_action :set_application, :except => [:waiting]
  before_action :can_approve_reject?, only: [:approve, :reject]
  before_action :already_approved_rejected?, only: [:approve, :reject]
  after_action :approve_reject_deployment, only: [:approve, :reject]

  swagger_controller :approvals, 'Approval Management'

  swagger_api :index do
    summary 'Fetches all Approval items'
    notes 'This lists all the Approvals'
    param :header, 'X-User-Email', :string, :required, 'User Email'
    param :header, 'X-User-Token', :string, :required, 'User Token'
  end

  swagger_api :show do
    summary 'Fetches a single Approval item'
    param :header, 'X-User-Email', :string, :required, 'User Email'
    param :header, 'X-User-Token', :string, :required, 'User Token'
    param :path, :id, :integer, :required, 'Approval ID'
    param :path, :deployment_environment_id, :integer, :required, 'Deployment Environment ID'
    param :path, :deployment_id, :integer, :required, 'Deployment ID'
    param :path, :application_id, :integer, :required, 'Application ID'
  end

  swagger_api :approve do
    summary 'Approve the Approval'
    param :header, 'X-User-Email', :string, :required, 'User Email'
    param :header, 'X-User-Token', :string, :required, 'User Token'
    param :path, :id, :integer, :required, 'Approval ID'
    param :path, :deployment_environment_id, :integer, :required, 'Deployment Environment ID'
    param :path, :deployment_id, :integer, :required, 'Deployment ID'
    param :path, :application_id, :integer, :required, 'Application ID'
  end

  swagger_api :reject do
    summary 'Reject the Approval'
    param :header, 'X-User-Email', :string, :required, 'User Email'
    param :header, 'X-User-Token', :string, :required, 'User Token'
    param :path, :id, :integer, :required, 'Approval ID'
    param :path, :deployment_environment_id, :integer, :required, 'Deployment Environment ID'
    param :path, :deployment_id, :integer, :required, 'Deployment ID'
    param :path, :application_id, :integer, :required, 'Application ID'
  end

  swagger_api :waiting do
    summary 'Approvals waiting'
    param :header, 'Authentication-Token', :string, :required, 'Authentication token'
  end

  # GET /api/applications/:application_id/deployments/:deployment_id/deployment_environments/:deployment_environment_id/approvals.json
  def index
    @approvals = @deployment.approvals
  end

  # GET /api/applications/:application_id/deployments/:deployment_id/deployment_environments/:deployment_environment_id/approvals/:id.json
  def show
  end

  # PUT/PATCH /api/applications/:application_id/deployments/:deployment_id/deployment_environments/:deployment_environment_id/approvals/:id/approve.json
  def approve
     respond_to do |format|
      if @approval.approve!(current_user, ActionController::Base.helpers.sanitize(params[:approver_comment]))
        format.json { render json: @approval, status: :created, location: api_application_deployment_deployment_environment_approval_path(@application, @deployment, @deployment_environment, @approval) }
      else
        format.json { render json: @approval.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT/PATCH /api/applications/:application_id/deployments/:deployment_id/deployment_environments/:deployment_environment_id/approvals/:id/reject.json
  def reject
    respond_to do |format|
      if @approval.reject!(current_user, ActionController::Base.helpers.sanitize(params[:approver_comment]))
        format.json { render json: @approval, status: :created, location: api_application_deployment_deployment_environment_approval_path(@application, @deployment, @deployment_environment, @approval) }
      else
        format.json { render json: @approval.errors, status: :unprocessable_entity }
      end
    end
  end

  def waiting
    @approvals = Approval.approvals_for_user(current_user)
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_approval
    @approval = Approval.find(params[:id])
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_application
    @application = Application.find(params[:application_id])
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_deployment
    @deployment = Deployment.find(params[:deployment_id])
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_deployment_environment
    @deployment_environment = DeploymentEnvironment.find(params[:deployment_environment_id])
  end

  def can_approve_reject?
    unless @approval.can_approve_reject? current_user
      respond_to do |format|
        format.json { render json: APIError::Exceptions.forbidden(Exception.new("You are not allowed to perform the '#{params[:action]}' action on this '#{params[:controller].split('/').last.singularize.titleize}'")), status: :unprocessable_entity }
      end
    end
  end

  def already_approved_rejected?
    if @approval.already_approved_rejected? && !current_user.has_role?(:approval_admin)
      respond_to do |format|
        format.json { render json: APIError::Exceptions.forbidden(Exception.new("You are not allowed to perform the '#{params[:action]}' action on this '#{params[:controller].split('/').last.singularize.titleize}' as its already #{@approval.current_state.to_s}")), status: :unprocessable_entity }
      end
    else
      already = false

      case params[:action].to_sym
        when :approve
          already = @approval.approved?
        when :reject
          already = @approval.rejected?
      end

      if already
        respond_to do |format|
          format.json { render json: APIError::Exceptions.forbidden(Exception.new("You are not allowed to perform the '#{params[:action]}' action on this '#{params[:controller].split('/').last.singularize.titleize}' as its already #{@approval.current_state.to_s}")), status: :unprocessable_entity }
        end
      end
    end
  end

  def approve_reject_deployment
    if @deployment_environment.approved?
      @deployment_environment.approve!
    elsif @deployment_environment.rejected?
      @deployment_environment.reject!
    end
  end
end

app/controllers/approvals_controller.rb
class ApprovalsController < ApplicationController
  load_and_authorize_resource
  before_action :set_approval, :except => [:index, :waiting]
  before_action :set_deployment, :except => [:waiting]
  before_action :set_application, :except => [:waiting]

  # GET /approvals
  def index
    @approvals = @deployment.approvals
  end

  # GET /approvals/1
  def show
  end

  def waiting
    @approvals = Approval.approvals_for_user(current_user)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_approval
      @approval = Approval.find(params[:id])
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_application
      @application = Application.find(params[:application_id])
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_deployment
      @deployment = Deployment.find(params[:deployment_id])
    end
end

app/helpers/api/v1/approvals_helper.rb
module API::V1::ApprovalsHelper
end

app/helpers/approvals_helper.rb
module ApprovalsHelper
  def show_approve_reject_links(approval)
    approval.can_approve_reject?(current_user) && !approval.already_approved_rejected?
  end

  # Check if object still exists in the database and display a link to it,
  # otherwise display a proper message about it.
  # This is used in activities that can refer to
  # objects which no longer exist, like removed posts.
  def link_to_trackable_approval(object, object_type)
    if object && object.deployment && object.deployment.application
      "#{link_to object.deployment.id, application_deployment_path(object.deployment.application, object.deployment)} for #{link_to object.deployment.application.name, object.deployment.application}".html_safe
    else
      "for an application which does not exist anymore"
    end
  end
end

app/views/approvals/_approvals.html.erb
<div class="approvals">
<script>
    <%= render partial: 'approvals/approve_reject', formats: [:js] %>
</script>
<div class="panel panel-default">
  <div class="panel-heading">
    <%= defined?(panel_title) ? panel_title : t('approvals.approvals') %>
  </div>
  <div class="panel-body">
    <table class='data_table' id="approvals_table">
      <thead>
      <tr>
        <th><%= t('applications.application') %></th>
        <th><%= t('deployments.deployment_id') %></th>
        <th><%= t('environments.environment') %></th>
        <th><%= t('general.created_on') %></th>
        <th><%= t('approvals.status') %></th>
        <th><%= t('general.actions.actions') %></th>
      </tr>
      </thead>
      <tbody>
      <% approvals.each do |approval| %>
          <tr id="approval_<%= approval.id %>">
            <td><%= link_to approval.deployment.application.name, approval.deployment.application %></td>
            <td><%= link_to approval.deployment.id, application_deployment_path(approval.deployment.application, approval.deployment) %></td>
            <td><%= approval.environment.name %></td>
            <td><%= link_to approval.created_at.strftime(t('general.timestamp_to_str')), application_deployment_deployment_environment_approval_path(approval.deployment.application, approval.deployment, approval.deployment_environment, approval) %></td>
            <td id="approval_<%= approval.id %>_status"><%= approval.current_state.to_s.titleize %></td>
            <td>
              <% if show_approve_reject_links(approval) %>
              <div id="approve_reject_links_<%= approval.id %>">
                <%= link_to t('approvals.approve'), '#', id: "approve_link_#{approval.id}", class: 'approve_link', data: { url: approve_api_application_deployment_deployment_environment_approval_path(approval.deployment.application, approval.deployment, approval.deployment_environment, approval) } %>
                <%= link_to t('approvals.reject'), '#', id: "reject_link_#{approval.id}", class: 'reject_link', data: { url: reject_api_application_deployment_deployment_environment_approval_path(approval.deployment.application, approval.deployment, approval.deployment_environment, approval) }  %>
              </div>
              <% end %>
            </td>
          </tr>
      <% end %>
      </tbody>
    </table>
  </div>
</div>
</div>

app/views/approvals/_approve_reject.js.erb
$(document).ready(function() {
    $('.approve_link').click(function() {
        show_approve_reject_dialog('<%= t('approvals.approve_deployment') %>', '<%= t('approvals.approve') %>', $(this).attr('data-url'));
    });

    $('.reject_link').click(function() {
        show_approve_reject_dialog('<%= t('approvals.reject_deployment') %>', '<%= t('approvals.reject') %>', $(this).attr('data-url'));
    });
});

function show_approve_reject_dialog(title, button_label, url, type) {
    if (type === undefined) {
        type = BootstrapDialog.TYPE_PRIMARY;
    }

    BootstrapDialog.show({
        title: title,
        message: '<form id="approver_comment_form"><h4><%= t('approvals.approver_comment') %>:</h4><textarea cols="67" name="approver_comment" id="approver_comment"></textarea></form>',
        type: type, // <-- Default value is BootstrapDialog.TYPE_PRIMARY
        closable: true, // <-- Default value is false
        draggable: true, // <-- Default value is false
        buttons: [{
            label: button_label,
            cssClass: 'btn-primary',
            hotkey: 13, // Enter.
            action: function(dialogRef) {
                var comment_text = $("#approver_comment_form").find("#approver_comment");
                $.ajax({
                    type: "POST",
                    url: url,
                    data: JSON.stringify({'approver_comment':comment_text.val()}),
                    dataType: 'json',
                    contentType: "application/json",
                    success: function (result) {
                        console.log(result);
                        displayNotice("The approval has been " + result.workflow_state);

                        var status_td = $('#approval_' + result.id + '_status');
                        var deployer_comment_td = $('#approval_' + result.id + '_approver_comment');

                        status_td.html((result.workflow_state.charAt(0).toUpperCase() + result.workflow_state.slice(1)).titleize());
                        deployer_comment_td.html(result.approver_comment);

                        status_td.effect("pulsate", {times:1}, 1000);
                        deployer_comment_td.effect("pulsate", {times:1}, 1000);

                        if (result.workflow_state == 'approved' || result.workflow_state == 'rejected') {
                            $("#approve_reject_links_" + result.id).hide();
                        }
                    },
                    error: function (xhr, ajaxOptions, thrownError) {
                        var json = jQuery.parseJSON(xhr.responseText);
                        displayAlert(json.message);
                    }
                });

                comment_text.val('');
                dialogRef.close();
            }
        }]
    });
}

app/views/approvals/index.html.erb
<h1><%= t('general.listing') % t('approvals.approvals') %></h1>

<%= render 'approvals', approvals: @approvals %>

app/views/approvals/show.html.erb
<script>
    <%= render partial: 'approve_reject', formats: [:js] %>
</script>
<h1><%= @approval.deployment.application.name.titleize %> - <%= @approval.deployment.id %></h1>
<br />
<div class="panel panel-default">
  <div class="panel-heading"><%= t('approvals.approval_attributes') %></div>

  <table class="table">
    <tr>
      <th><%= t('look_and_feel.account.attributes.name') %></th>
      <th><%= t('look_and_feel.account.attributes.attribute') %></th>
    </tr>
    <tr>
      <td><%= t('approvals.status') %></td>
      <td id="approval_<%= @approval.id %>_status"><%= @approval.current_state.to_s.titleize%></td>
    </tr>
    <tr>
      <td><%= t('approvals.approver_comment') %></td>
      <td id="approval_<%= @approval.id %>_approver_comment"><%= @approval.approver_comment %></td>
    </tr>
    <tr>
      <td><%= t('applications.application') %></td>
      <td><%= link_to @approval.deployment.application.name, application_path(@approval.deployment.application) %></td>
    </tr>
    <tr>
      <td><%= t('deployments.deployment') %></td>
      <td><%= link_to @approval.deployment.id, application_deployment_path(@approval.deployment.application, @approval.deployment) %></td>
    </tr>
    <tr>
      <td><%= t('environments.environment') %></td>
      <td><%= @approval.environment.name.titleize %></td>
    </tr>
    <tr>
      <td><%= t('general.actions.actions') %></td>
      <td>
        <% if show_approve_reject_links(@approval) %>
            <%= link_to t('approvals.approve'), '#', id: "approve_link_#{@approval.id}", class: 'approve_link', data: { url: approve_api_application_deployment_deployment_environment_approval_path(@approval.deployment.application, @approval.deployment, @approval.deployment_environment, @approval) } %>
            <%= link_to t('approvals.reject'), '#', id: "reject_link_#{@approval.id}", class: 'reject_link', data: { url: reject_api_application_deployment_deployment_environment_approval_path(@approval.deployment.application, @approval.deployment, @approval.deployment_environment, @approval) }  %>
        <% else %>
          <%= t('general.not_applicable') %>
        <% end %>
      </td>
    </tr>
  </table>
</div>

app/views/approvals/waiting.html.erb
<h1><%= t('general.listing') % t('approvals.your_awaiting_approvals') %></h1>

<%= render 'approvals', approvals: @approvals %>