config/routes.rb
Rails.application.routes.draw do
  authenticated :user do
    root :to => 'dashboards#home', :as => :authenticated_root
  end

  root :to => redirect('/users/sign_in')

  devise_for :users, :controllers => { :users => 'users', :registrations => 'registrations', :confirmations => 'confirmations', :password_expired => 'password_expired', :omniauth_callbacks => 'users/omniauth_callbacks' }
  devise_scope :user do
    put '/confirm' => 'confirmations#confirm'
  end

  resource :my_account, :controller => :my_account, :only => [:show]  do
    resource :password_expired, :only => [:show, :update], :controller => :password_expired
  end

  resources :applications do
    resources :environments
    resources :deployments do
      resources :deployment_environments, only: [:index, :show, :output] do
        member do
          get :output
        end
        resources :approvals, :only => [:index, :show]
      end
    end
  end

  resources :approval_groups, :only => [:index, :show]
  resources :deployment_templates
  resources :dashboards, :only => [:index, :show, :home] do
    collection do
      get :home
    end
  end

  resources :approvals, :only => [:waiting] do
    collection do
      get :waiting
    end
  end

  namespace :admin do
    match '/' => 'admin#index', via: :get
    resources :approval_groups, :controllers => { :roles => 'admin/approval_groups' }
    resources :audits, only: [:index, :show]
    resources :dashboards, :controllers => { :dashboards => 'admin/dashboards' }, only: [:index]
    resources :deployment_modules, :controllers => { :roles => 'admin/deployment_modules' }, except: [:new, :create] do
      collection do
        get :upload
        post :perform_upload
      end

      member do
        get :upgrade
        patch :perform_upgrade
      end
    end
    resources :mailer_notification_permissions, :controllers => { :mailer_notification_permissions => 'admin/mailer_notification_permissions' }, :only => [:index]
    resources :roles, :controllers => { :roles => 'admin/roles' }, :only => [:index, :show]
    resources :users,  :controllers => { :users => 'admin/users'}
  end

  namespace :api, :defaults => {:format => :html} do
    root :to => 'api#index'

    resources :api, :controller => :api

    scope module: :v1, constraints: ApiConstraints.new(version: 1, default: true), :defaults => {:format => :json} do
      resources :applications, :only => [:index, :show] do
        member do
          put :watch
          delete :unwatch
        end
        resources :deployments, :only => [:index, :show, :deploy, :create, :update] do
          member do
            post :deploy
            put :watch
            delete :unwatch
          end
          resources :deployment_environments, :only => [:deploy, :destroy, :update_schedule, :cancel_schedule] do
            member do
              post :deploy
              delete :destroy
              patch :update_schedule
              delete :cancel_schedule
            end
            resources :approvals, :only => [:index, :show, :approve, :reject] do
              member do
                post :approve
                post :reject
              end
            end
          end
        end
        resources :environments, :only => [:index, :show, :destroy] do
          member do
            post :deploy
            delete :destroy
          end
        end
      end
      resources :audits, only: [:index, :show]
      resources :deployment_templates
      resources :deployment_modules, only: [:index, :show]
      resources :charts, only: [:approvals_per_deployment, :deployments_per_application] do
        collection do
          get :approvals_per_deployment
          get :deployments_per_application
          get :deployments_created_last_x_days
        end
      end
      resources :approvals, :only => [:waiting] do
        collection do
          get :waiting
        end
      end
      resources :users, only: [:index, :show]
    end
  end
end

app/models/application.rb
class Application < ActiveRecord::Base
  include TicketingSystems::ActsAsTicketable
  include PublicActivity::Model

  acts_as_ticketable
  audited
  has_associated_audits
  tracked :owner => proc {|controller, model| controller ? controller.current_user : model.user}


  belongs_to :deployment_module
  belongs_to :user

  has_many :deployments, dependent: :destroy
  has_many :deployment_templates, dependent: :nullify
  has_many :approval_group_applications, dependent: :destroy
  has_many :environments, dependent: :destroy
  has_many :resource_cc_users, as: :ccable, dependent: :destroy
  has_many :watchers, as: :watchable, dependent: :destroy

  has_many :resource_ticketing_system_permissions, as: :resource, dependent: :destroy

  has_many :approval_groups, through: :approval_group_applications
  has_many :cc_users, :through => :resource_cc_users, :source => :user
  has_many :ticketing_system_permissions, through: :resource_ticketing_system_permissions


  accepts_nested_attributes_for :environments, allow_destroy: true, :reject_if => proc { |e| e[:name].blank? }
  accepts_nested_attributes_for :approval_group_applications
  accepts_nested_attributes_for :resource_cc_users
  accepts_nested_attributes_for :resource_ticketing_system_permissions

  validates :name, presence: true, uniqueness: true
  validates :deployment_module_id, presence: true
  validate :valid_environment?

  before_save :mark_environments_for_removal

  serialize :deployment_parameters, Hash

  def approvers
    self.approval_groups.map { |ag| ag.users }.flatten
  end

  def needs_approvals?
    self.approval_count > 0
  end

  def to_s
    self.name
  end

  def mailing_list
    users = []
    users += self.approvers
    users += self.cc_users
    users += self.watchers.map(&:user).flatten
    users <<  self.user unless self.user.nil? || self.approvers.include?(self.user)

    users.flatten.uniq
  end

  private
  def mark_environments_for_removal
    self.environments.each do |environments|
      environments.mark_for_destruction if environments.name.blank? && environments.deployment_order.blank?
    end
  end

  def valid_environment?
    errors.add(:base, 'At least one environment must be created.') unless self.environments.length > 0

    deployment_orders = self.environments.map(&:deployment_order)

    unless deployment_orders.uniq.length == deployment_orders.length
      errors.add(:environments, 'must have deployment order set uniquely.')
    end
  end
end

app/controllers/api/v1/applications_controller.rb
class API::V1::ApplicationsController < ApplicationController
  load_and_authorize_resource
  before_action :set_application, only: [:watch, :unwatch]

  swagger_controller :applications, 'Application Management'

  swagger_api :watch do
    summary 'Adds the accessing user to the watchers list for the Application'
    param :header, 'X-User-Email', :string, :required, 'User Email'
    param :header, 'X-User-Token', :string, :required, 'User Token'
    param :path, :id, :integer, :required, 'Application ID'
  end

  swagger_api :unwatch do
    summary 'Removes the accessing user from the watchers list for the Application'
    param :header, 'X-User-Email', :string, :required, 'User Email'
    param :header, 'X-User-Token', :string, :required, 'User Token'
    param :path, :id, :integer, :required, 'Application ID'
  end


  # PUT /api/applications/:id/watch.json
  def watch
    @application.watchers.new(user: current_user)

    respond_to do |format|
      if @application.save
        format.json { render partial: 'watch', status: :created, location: application_path(@application) }
      else
        format.json { render json: @application.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /api/applications/:id/unwatch.json
  def unwatch
    respond_to do |format|
      if @application.watchers.find_by_user_id(current_user.id).destroy
        format.json { render partial: 'unwatch', status: 200 }
      else
        format.json { render json: @application.errors, status: :unprocessable_entity }
      end
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_application
    @application = Application.find(params[:id])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :null_session

  include PublicActivity::StoreController
  include ActionView::Helpers::TextHelper

  before_filter :set_timezone

  rescue_from CanCan::AccessDenied do |exception|
    if user_signed_in?
      session[:user_return_to] = nil

      if params[:redirect_to]
        redirect_path = params[:redirect_to]
      else
        redirect_path = root_path
      end

      respond_to do |format|
        format.html { redirect_to redirect_path, :flash => { alert: t('user.not_authorized') } }
        format.json { render json: { :message => t('user.not_authorized'), :url => request.url } }
        format.js { render js: "displayAlert('#{t('user.not_authorized_action') % [params[:action], params[:controller].titleize]}!');", :status => :forbidden }
      end

    else
      session[:user_return_to] = request.url

      respond_to do |format|
        format.html { redirect_to '/users/sign_in', :flash => { alert: t('user.login_first') } }
        format.json { render json: { :message => t('user.login_first'), :url => request.url } }
      end
    end
  end

  def set_timezone
    Time.zone = current_user.time_zone if current_user
  end

  def deployment_parameters_to_string(deployment_parameters)
    if deployment_parameters.is_a?(Hash)
      params = ''

      deployment_parameters.each do |k,v|
        params += "#{k}: #{v}\n"
      end

      params
    else
      deployment_parameters
    end
  end

  private
  def after_sign_out_path_for(resource_or_scope)
    new_user_session_path
  end

  def after_sign_in_path_for(resource)
    session[:omniauth_redirect_to] || stored_location_for(resource) || root_path
  end
end

app/controllers/applications_controller.rb
class ApplicationsController < ApplicationController
  load_and_authorize_resource

  before_action :set_application, only: [:show, :edit, :update, :destroy]
  before_action :set_cc_users, only: [:edit, :update]

  # GET /applications
  def index
    @applications = Application.all
  end

  # GET /applications/1
  def show
  end

  # GET /applications/new
  def new
    @application = Application.new
    @application.environments.build

    @application.add_ticketable_permissions

    @deployment_parameters = @application.deployment_parameters.to_yaml
  end

  # GET /applications/1/edit
  def edit
    @deployment_parameters = deployment_parameters_to_string(@application.deployment_parameters) || params[:deployment_parameters]
    @application.environments.build
  end

  # POST /applications
  def create
    @application = current_user.applications.new(application_params)

    respond_to do |format|
      if @application.save
        ApplicationsMailer.delay.new_notification(@application)
        format.html { redirect_to @application, notice: 'Application was successfully created.' }
      else
        @deployment_parameters = deployment_parameters_to_string(@application.deployment_parameters) || params[:deployment_parameters]
        @application.environments.build
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /applications/1
  def update
    respond_to do |format|
      if @application.update(application_params)
        format.html { redirect_to @application, notice: 'Application was successfully updated.' }
      else
        @deployment_parameters = deployment_parameters_to_string(@application.deployment_parameters) || params[:deployment_parameters]
        format.html { render :edit }
      end
    end
  end

  # DELETE /applications/1
  def destroy
    application_name = @application.name
    destroy_user = current_user
    mailing_list = @application.mailing_list

    @application.destroy

    ApplicationsMailer.delay.destroy_notification(application_name, destroy_user, mailing_list)

    respond_to do |format|
      format.html { redirect_to applications_url, notice: 'Application was successfully destroyed.' }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_application
      @application = Application.find(params[:id])
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_cc_users
      @cc_users = @application.cc_users
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def application_params
      safe_param = params.require(:application).permit!#(:name, :deployment_module_id, :deployment_parameters, :approval_count, :allow_self_approval, approval_group_ids: [],
                                          # resource_ticketing_system_permissions_attributes: [:id, :enabled, :ticketing_system_permission_id],
                                          # environments_attributes: [:id, :name, :deployment_order, deployment_parameters: {}])
      safe_param.merge(
          deployment_parameters: YAML.load(params[:application][:deployment_parameters]) || {},
          environments_attributes: environments_deployment_parameters_to_hash(params[:application][:environments_attributes])
      )
    end

    def environments_deployment_parameters_to_hash(environments_attributes)
      if environments_attributes
        environments_attributes.keys.each do |k|
          if environments_attributes[k][:deployment_parameters].is_a?(String)
            environments_attributes[k][:deployment_parameters] = YAML.load(environments_attributes[k][:deployment_parameters]) || {}
          end
        end
      end

      environments_attributes || []
    end
end

app/helpers/api/v1/applications_helper.rb
module API::V1::ApplicationsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def boolean_to_string(bool)
    case bool
      when 0, false, 'false', 'FALSE', 'False'
        t('general.boolean_no')
      when 1, true, 'true', 'TRUE', 'True'
        t('general.boolean_yes')
    end
  end

  def deployment_parameters_to_string(deployment_parameters)
    if deployment_parameters.is_a?(Hash)
      params = ''

      deployment_parameters.each do |k,v|
        params += "#{k}: #{v}\n"
      end

      params
    else
      deployment_parameters
    end
  end

  def cc_users_js(cc_users)
    "<script>var previous_cc_users_array = [#{raw (cc_users.map{|u| { id: u.id, full_name: u.full_name, email: u.email, gravatar_url: u.gravatar_url }}).to_json}]</script>".html_safe
  end
end

app/helpers/applications_helper.rb
module ApplicationsHelper
  def environment_deployment_params(environment_index, application, environment)
    if params[:application] && params[:application][:environments_attributes] && params[:application][:environments_attributes][environment_index.to_s]
      if params[:application][:environments_attributes][environment_index.to_s]['deployment_parameters'].is_a?(String)
        params[:application][:environments_attributes][environment_index.to_s]['deployment_parameters']
      else
        deployment_parameters_to_string(params[:application][:environments_attributes][environment_index.to_s]['deployment_parameters'])
      end
    else
      application.deployment_module ? application.deployment_module.default_parameters_environments.merge(environment.deployment_parameters).to_yaml : environment.deployment_parameters.to_yaml
    end
  end

  def akamai_cp_codes_to_string(akamai_cp_codes_array)
    akamai_cp_codes_array ? akamai_cp_codes_array.join(', ') : ''
  end
end

app/views/applications/_applications.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <%= defined?(panel_title) ? panel_title : t('applications.applications') %>
  </div>
  <div class="panel-body">
    <table class='data_table' id="applications_table">
      <thead>
      <tr>
        <th><%= t('applications.name') %></th>
        <th><%= t('deployment_modules.deployment_module') %></th>
        <th><%= t('general.created_by') %></th>
        <th><%= t('general.created_on') %></th>
        <th><%= t('general.actions.actions') %></th>
      </tr>
      </thead>
      <tbody>
      <% applications.each do |application| %>
          <tr id="application_<%= application.id %>">
            <td><%= link_to application.name, application_path(application) %></td>
            <td><%= application.deployment_module %></td>
            <td><%= application.user %></td>
            <td><%= application.created_at.strftime(t('general.timestamp_to_str')) %></td>
            <td>
              <%= link_to t('applications.create_deployment'), new_application_deployment_path(application) if can? :create, Deployment %>
              <%= link_to t('general.actions.edit'), edit_application_path(application) if can? :edit, Application %>
              <%= link_to t('general.actions.delete'), application_path(application), :confirm => t('general.are_you_sure'), :method => :delete if can? :destroy, Application %>
              <%= render partial: 'shared/watch_unwatch', locals: { resource: application, user: current_user } %>
            </td>
          </tr>
      <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/applications/_form.html.erb
<%= form_for(@application) do |f| %>
  <% if @application.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@application.errors.count, t('general.error')) %> prohibited this application from being saved:</h2>

      <ul>
      <% @application.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <div class="container-fluid">
      <div class="row">
        <div class="col-md-5">
          <div class="panel panel-default">
            <div class="panel-heading">
              <%= t('applications.application_information') %>
            </div>
            <div class="panel-body">
              <div class="field">
                <%= f.label :name %><br>
                <%= f.text_field :name %>
              </div>
              <div class="field">
                <%= f.label :deployment_module %>
                <%= f.collection_select :deployment_module_id, DeploymentModule.all.sort_by { |dm| dm.name }, :id, :name, { include_blank: true } %>
              </div>
              <div class="field">
                <%= f.label :deployment_parameters %>
                <%= f.text_area :deployment_parameters, value: @deployment_parameters %>
              </div>
              <div class="field">
                <%= f.label :cc_users, t('applications.cc') %>
                <%= f.collection_select :cc_user_ids, @application.cc_users, :id, :name, {}, { multiple: true, style: 'width: 250px', class: 'cc_user_ids'} %>
                <%= cc_users_js(@cc_users) if @cc_users %>
              </div>
            </div>
          </div>
          <div class="panel panel-default">
            <div class="panel-heading">
              <%= t('environments.environments') %>
            </div>
            <div class="panel-body">
              <div id="environments">
                <h3><%= t('environments.environments') %>
                  <span class='actions'><%= link_to t('general.add'), '', :class => 'duplicate_nested_form' %></span>
                </h3>
                <%= f.fields_for :environments do |environment_form| %>
                    <div class="duplicatable_nested_form">
                      <div class="field">
                        <%= environment_form.label :name %>
                        <%= environment_form.text_field :name %>
                      </div>
                      <div class="field">
                        <%= environment_form.label :deployment_parameters %>
                        <%= environment_form.text_area :deployment_parameters, value: environment_deployment_params(environment_form.index, @application, environment_form.object), class: 'application_environments_attributes_deployment_parameters' %>
                      </div>
                      <div class="field">
                        <%= environment_form.label :deployment_order %>
                        <%= environment_form.number_field :deployment_order %>
                      </div>
                      <% if AppConfig.get(%W(akamai_purge enable), APP_CONFIG) %>
                        <div class="field">
                          <%= environment_form.label :akamai_cp_codes, t('akamai_purge.akamai_cp_codes') %>
                          <%= environment_form.text_field :akamai_cp_codes, value: akamai_cp_codes_to_string(environment_form.object.akamai_cp_codes) %>
                        </div>
                      <% end %>
                      <div class="field">
                        <% if environment_form.object.new_record? %>
                            <%= link_to t('general.remove'), '', :remote => true, :class => 'destroy_duplicate_nested_form' %>
                        <% else %>
                            <%= link_to t('general.remove'), api_application_environment_path(@application, environment_form.object), :method => :delete, :remote => true, :class => 'destroy_duplicate_nested_form', :format => :json %>
                            <%= environment_form.hidden_field(:id) %>
                        <% end %>
                      </div>
                    </div>
                <% end %>
              </div>
            </div>
          </div>
        </div>
        <div class="col-md-7">
          <div class="panel panel-default">
            <div class="panel-heading">
              <%= t('approvals.approvals') %>
            </div>
            <div class="panel-body">
              <div class="field">
                <%= f.label :approval_count %>
                <%= f.number_field :approval_count %>
              </div>
              <div class="field">
                <%= f.label :approval_groups %>
                <%= f.collection_select :approval_group_ids, ApprovalGroup.all.sort_by { |ag| ag.name }, :id, :name, {}, { multiple: true } %>
              </div>
              <div class="field">
                <%= f.label :allow_self_approval, t('applications.allow_self_approval') %>
                <%= f.check_box :allow_self_approval %>
              </div>
            </div>
          </div>
          <% if ticketing_system_enabled?(:jira) %>
          <div class="panel panel-default">
            <div class="panel-heading">
              <%= t('resource_ticketing_system_permissions.resource_ticketing_system_permissions') %>
            </div>
            <div class="panel-body">
              <%= render 'shared/resource_ticketing_system_permissions_fields', form: f, resource: @application %>
            </div>
          </div>
          <% end %>
        </div>
      </div>
      <div class="row">
        <div class="col-md-12">
          <div style="margin: auto;
                  width: 60%;
                  padding: 10px;">
            <%= f.submit %>
          </div>
        </div>
      </div>
    </div>
<% end %>

app/views/applications/edit.html.erb
<h1><%= t('general.editing') % @application.name %></h1>

<%= render 'form' %>
<br />
<br />
<br />
<%= link_to t('general.actions.back'), :back %>

app/views/applications/index.html.erb
<h1><%= t('general.listing') % t('applications.applications') %></h1>

<%= render 'applications', applications: @applications %>

<% if can? :create, Application %>
<span class='actions'>
  <%= link_to t('general.actions.new'), new_application_path %>
</span>
<% end %>

app/views/applications/new.html.erb
<h1><%= t('general.new') % t('applications.application') %></h1>

<%= render 'form' %>
<br />
<br />
<br />
<%= link_to t('general.actions.back'), applications_path %>

app/views/applications/show.html.erb
<h1><%= @application.name.titleize %>
  <% if can? :create, Deployment %>
    <span class='actions'><%= link_to t('applications.create_deployment'), new_application_deployment_path(@application) %></span>
  <% end %></h1>
<br />
<div class="container-fluid">
  <div class="row">
    <div class="col-md-4">
      <div class="panel panel-default">
        <div class="panel-heading"><%= t('applications.applications_attributes') %></div>
        <table class="table">
          <tr>
            <th><%= t('look_and_feel.account.attributes.name') %></th>
            <th><%= t('look_and_feel.account.attributes.attribute') %></th>
          </tr>
          <tr>
            <td><%= t('applications.number_of_approvals_needed') %></td>
            <td><%= @application.approval_count %></td>
          </tr>
          <tr>
            <td><%= t('deployment_modules.deployment_module') %></td>
            <td><%= @application.deployment_module %></td>
          </tr>
          <tr>
            <td><%= t('applications.deployment_parameters') %></td>
            <td><%= @application.deployment_parameters %></td>
          </tr>
          <% if @application.needs_approvals? %>
          <tr>
            <td><%= t('applications.can_self_approve') %></td>
            <td><%= @application.allow_self_approval %></td>
          </tr>
          <% end %>
        </table>
      </div>
      <%= render 'shared/people', { resource: @application, api_url: api_application_path(@application)} %>
      <%= render 'environments/environments', { environments: @application.environments } %>
      <%= render('approval_groups/approval_groups', { approval_groups: @application.approval_groups }) if @application.needs_approvals? %>
    </div>
    <div class="col-md-8">
      <%= render 'deployments/deployments', { deployments: @application.deployments } %>
    </div>
  </div>
</div>
<br />
<span class='actions'>
<% if can? :edit, Application %>
<%= link_to 'Edit', edit_application_path(@application) %>
<% end %>
  <%= link_to 'Back', :back %>
</span>