config/routes.rb
Rails.application.routes.draw do
  authenticated :user do
    root :to => 'dashboards#home', :as => :authenticated_root
  end

  root :to => redirect('/users/sign_in')

  devise_for :users, :controllers => { :users => 'users', :registrations => 'registrations', :confirmations => 'confirmations', :password_expired => 'password_expired', :omniauth_callbacks => 'users/omniauth_callbacks' }
  devise_scope :user do
    put '/confirm' => 'confirmations#confirm'
  end

  resource :my_account, :controller => :my_account, :only => [:show]  do
    resource :password_expired, :only => [:show, :update], :controller => :password_expired
  end

  resources :applications do
    resources :environments
    resources :deployments do
      resources :deployment_environments, only: [:index, :show, :output] do
        member do
          get :output
        end
        resources :approvals, :only => [:index, :show]
      end
    end
  end

  resources :approval_groups, :only => [:index, :show]
  resources :deployment_templates
  resources :dashboards, :only => [:index, :show, :home] do
    collection do
      get :home
    end
  end

  resources :approvals, :only => [:waiting] do
    collection do
      get :waiting
    end
  end

  namespace :admin do
    match '/' => 'admin#index', via: :get
    resources :approval_groups, :controllers => { :roles => 'admin/approval_groups' }
    resources :audits, only: [:index, :show]
    resources :dashboards, :controllers => { :dashboards => 'admin/dashboards' }, only: [:index]
    resources :deployment_modules, :controllers => { :roles => 'admin/deployment_modules' }, except: [:new, :create] do
      collection do
        get :upload
        post :perform_upload
      end

      member do
        get :upgrade
        patch :perform_upgrade
      end
    end
    resources :mailer_notification_permissions, :controllers => { :mailer_notification_permissions => 'admin/mailer_notification_permissions' }, :only => [:index]
    resources :roles, :controllers => { :roles => 'admin/roles' }, :only => [:index, :show]
    resources :users,  :controllers => { :users => 'admin/users'}
  end

  namespace :api, :defaults => {:format => :html} do
    root :to => 'api#index'

    resources :api, :controller => :api

    scope module: :v1, constraints: ApiConstraints.new(version: 1, default: true), :defaults => {:format => :json} do
      resources :applications, :only => [:index, :show] do
        member do
          put :watch
          delete :unwatch
        end
        resources :deployments, :only => [:index, :show, :deploy, :create, :update] do
          member do
            post :deploy
            put :watch
            delete :unwatch
          end
          resources :deployment_environments, :only => [:deploy, :destroy, :update_schedule, :cancel_schedule] do
            member do
              post :deploy
              delete :destroy
              patch :update_schedule
              delete :cancel_schedule
            end
            resources :approvals, :only => [:index, :show, :approve, :reject] do
              member do
                post :approve
                post :reject
              end
            end
          end
        end
        resources :environments, :only => [:index, :show, :destroy] do
          member do
            post :deploy
            delete :destroy
          end
        end
      end
      resources :audits, only: [:index, :show]
      resources :deployment_templates
      resources :deployment_modules, only: [:index, :show]
      resources :charts, only: [:approvals_per_deployment, :deployments_per_application] do
        collection do
          get :approvals_per_deployment
          get :deployments_per_application
          get :deployments_created_last_x_days
        end
      end
      resources :approvals, :only => [:waiting] do
        collection do
          get :waiting
        end
      end
      resources :users, only: [:index, :show]
    end
  end
end

app/models/approval_group.rb
class ApprovalGroup < ActiveRecord::Base
  audited

  has_many :approval_group_applications, dependent: :delete_all
  has_many :approval_group_users, dependent: :delete_all

  has_many :applications, :through => :approval_group_applications
  has_many :users, :through => :approval_group_users

  accepts_nested_attributes_for :approval_group_users

  validates :name, presence: true, uniqueness: true
end

app/controllers/admin/approval_groups_controller.rb
class Admin::ApprovalGroupsController < Admin::BaseController
  load_and_authorize_resource

  def index
    @approval_groups = ApprovalGroup.all
  end

  def show
    @approval_group = ApprovalGroup.find(params[:id])
  end

  def new
    @approval_group = ApprovalGroup.new
    @approvers = User.all.select { |u| u.has_role?(:approver) } || []
  end

  def create
    @approval_group = ApprovalGroup.new(approval_group_params)
    @approvers = User.all.select { |u| u.has_role?(:approver) } || []

    if @approval_group.save
      flash[:notice] = "#{t('approval_groups.created')} - #{@approval_group.name}"
      redirect_to admin_approval_groups_path
    else
      render :action => 'new'
    end
  end

  def edit
    @approval_group = ApprovalGroup.find(params[:id])
    @approvers = User.all.select { |u| u.has_role?(:approver) } || []
  end

  def update
    @approval_group = ApprovalGroup.find(params[:id])
    @approvers = User.all.select { |u| u.has_role?(:approver) } || []

    respond_to do |format|
      if @approval_group.update_attributes(approval_group_params)
        format.html { redirect_to session[:user_return_to] ? session[:user_return_to] : admin_approval_groups_path, notice: "#{t('approval_groups.updated')} - #{@approval_group.name}" }
      else
        format.html { render action: "edit" }
      end
    end
  end

  def destroy
    @approval_group = ApprovalGroup.find(params[:id]).destroy

    flash[:notice] = "#{t('approval_groups.deleted')} - #{@approval_group.name}"

    respond_to do |format|
      format.html { redirect_to admin_approval_groups_path }
      format.json { head :no_content }
    end
  end

  private
  def approval_group_params
    params.require(:approval_group).permit(:name, :description, user_ids: [])
  end
end

app/controllers/approval_groups_controller.rb
class ApprovalGroupsController < ApplicationController
  load_and_authorize_resource

  def index
    @approval_groups = ApprovalGroup.all
  end

  def show
    @approval_group = ApprovalGroup.find(params[:id])
  end
end

app/helpers/admin/approval_groups_helper.rb
module Admin::ApprovalGroupsHelper
end

app/helpers/approval_groups_helper.rb
module ApprovalGroupsHelper
end

app/views/admin/approval_groups/_approval_groups.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <%= t('approval_groups.approval_groups') %>
  </div>
  <div class="panel-body">
    <table class='data_table' id="server_groups_table">
      <thead>
      <tr>
        <th><%= t('approval_groups.name') %></th>
        <th><%= t('approval_groups.description') %></th>
        <th><%= t('general.actions.actions') %></th>
      </tr>
      </thead>
      <tbody>
      <% approval_groups.each do |approval_group| %>
          <tr id="approval_group_<%= approval_group.id %>">
            <td><%= link_to approval_group.name, admin_approval_group_path(approval_group) %></td>
            <td><%= approval_group.description %></td>
            <td>
              <%= link_to t('general.actions.edit'), edit_admin_approval_group_path(approval_group) %>
              <%= link_to t('general.actions.delete'), admin_approval_group_path(approval_group), :confirm => t('general.are_you_sure'), :method => :delete %>
            </td>
          </tr>
      <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/admin/approval_groups/_form.html.erb
    <% if @approval_group.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@approval_group.errors.count, "error") %> prohibited this approval group from being saved:</h2>

          <ul>
            <% @approval_group.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>
    <div class="field">
      <%= f.label :name %><br />
      <%= f.text_field :name, :autofocus => true %>
    </div>
    <div class="field">
      <%= f.label :description %><br />
      <%= f.text_area :description %>
    </div>
    <div class="field">
      <%= f.label :users %>
      <%= f.collection_select :user_ids, @approvers.sort_by{ |u| u.email },:id, :full_name_with_email, {}, { multiple: true } %>
    </div>

app/views/admin/approval_groups/edit.html.erb
<h1><%= t('general.actions.edit') % @approval_group.name %></h1>

<%= form_for(@approval_group, :url => admin_approval_group_path) do |f| %>
    <%= render 'form', f: f %>

    <div class="actions">
      <%= f.submit t('approval_groups.update') %>
    </div>
<% end %>
<br />
<br />
<br />
<%= link_to t('general.actions.back'),:back %>

app/views/admin/approval_groups/index.html.erb
<br />
<%= render 'approval_groups', approval_groups: @approval_groups %>

<% if can? :create, ApprovalGroup %>
    <span class='actions'>
      <%= link_to t('general.actions.new'), new_admin_approval_group_path, :id => 'new_admin_approval_group_link' %>
    </span>
<% end %>

app/views/admin/approval_groups/new.html.erb
<h1><%= t('general.new') % t('approval_groups.approval_group') %></h1>

<%= form_for(@approval_group, :url => admin_approval_groups_path) do |f| %>
    <%= render 'form', f: f %>

    <div class="actions">
      <%= f.submit t('approval_groups.create') %>
    </div>
<% end %>
<br />
<br />
<br />
<%= link_to t('general.actions.back'), :back %>

app/views/admin/approval_groups/show.html.erb
<h1><%= @approval_group.name.titleize %></h1>
<br />
<div class="panel panel-default">
  <div class="panel-heading"><%= t('approval_groups.approval_group_attributes') %></div>

  <table class="table">
    <tr>
      <th><%= t('look_and_feel.account.attributes.name') %></th>
      <th><%= t('look_and_feel.account.attributes.attribute') %></th>
    </tr>
    <tr>
      <td><%= t('approval_groups.description') %></td>
      <td><%= @approval_group.description %></td>
    </tr>
  </table>
</div>
<br />
<%= render 'admin/users/users', { users: @approval_group.users, panel_title: t('approval_groups.associated_users')} %>