config/routes.rb
Rails.application.routes.draw do
  authenticated :user do
    root :to => 'dashboards#home', :as => :authenticated_root
  end

  root :to => redirect('/users/sign_in')

  devise_for :users, :controllers => { :users => 'users', :registrations => 'registrations', :confirmations => 'confirmations', :password_expired => 'password_expired', :omniauth_callbacks => 'users/omniauth_callbacks' }
  devise_scope :user do
    put '/confirm' => 'confirmations#confirm'
  end

  resource :my_account, :controller => :my_account, :only => [:show]  do
    resource :password_expired, :only => [:show, :update], :controller => :password_expired
  end

  resources :applications do
    resources :environments
    resources :deployments do
      resources :deployment_environments, only: [:index, :show, :output] do
        member do
          get :output
        end
        resources :approvals, :only => [:index, :show]
      end
    end
  end

  resources :approval_groups, :only => [:index, :show]
  resources :deployment_templates
  resources :dashboards, :only => [:index, :show, :home] do
    collection do
      get :home
    end
  end

  resources :approvals, :only => [:waiting] do
    collection do
      get :waiting
    end
  end

  namespace :admin do
    match '/' => 'admin#index', via: :get
    resources :approval_groups, :controllers => { :roles => 'admin/approval_groups' }
    resources :audits, only: [:index, :show]
    resources :dashboards, :controllers => { :dashboards => 'admin/dashboards' }, only: [:index]
    resources :deployment_modules, :controllers => { :roles => 'admin/deployment_modules' }, except: [:new, :create] do
      collection do
        get :upload
        post :perform_upload
      end

      member do
        get :upgrade
        patch :perform_upgrade
      end
    end
    resources :mailer_notification_permissions, :controllers => { :mailer_notification_permissions => 'admin/mailer_notification_permissions' }, :only => [:index]
    resources :roles, :controllers => { :roles => 'admin/roles' }, :only => [:index, :show]
    resources :users,  :controllers => { :users => 'admin/users'}
  end

  namespace :api, :defaults => {:format => :html} do
    root :to => 'api#index'

    resources :api, :controller => :api

    scope module: :v1, constraints: ApiConstraints.new(version: 1, default: true), :defaults => {:format => :json} do
      resources :applications, :only => [:index, :show] do
        member do
          put :watch
          delete :unwatch
        end
        resources :deployments, :only => [:index, :show, :deploy, :create, :update] do
          member do
            post :deploy
            put :watch
            delete :unwatch
          end
          resources :deployment_environments, :only => [:deploy, :destroy, :update_schedule, :cancel_schedule] do
            member do
              post :deploy
              delete :destroy
              patch :update_schedule
              delete :cancel_schedule
            end
            resources :approvals, :only => [:index, :show, :approve, :reject] do
              member do
                post :approve
                post :reject
              end
            end
          end
        end
        resources :environments, :only => [:index, :show, :destroy] do
          member do
            post :deploy
            delete :destroy
          end
        end
      end
      resources :audits, only: [:index, :show]
      resources :deployment_templates
      resources :deployment_modules, only: [:index, :show]
      resources :charts, only: [:approvals_per_deployment, :deployments_per_application] do
        collection do
          get :approvals_per_deployment
          get :deployments_per_application
          get :deployments_created_last_x_days
        end
      end
      resources :approvals, :only => [:waiting] do
        collection do
          get :waiting
        end
      end
      resources :users, only: [:index, :show]
    end
  end
end

app/models/deployment_module.rb
require 'zip'

class DeploymentModule < ActiveRecord::Base
  audited

  has_many :applications

  validates :name, presence: true, uniqueness: true
  validates :module_version, presence: true

  serialize :module_files, Array

  serialize :settings, Hash
  serialize :default_parameters_applications, Hash
  serialize :default_parameters_environments, Hash
  serialize :default_parameters_deployments, Hash

  before_destroy :remove_module_directory

  def to_s
    self.name
  end

  def self.available_modules
    dir = Rails.root.join(DeploymentModule.module_directory)

    modules = []

    Dir.foreach(dir) do |item|
      next if item == '.' or item == '..'

      begin
        module_yaml = File.join(dir, item, "#{item}.yml")
        module_rb = File.join(dir, item, "#{item}.rb")

        next unless File.exist?(module_yaml) && File.exist?(module_rb)



        module_info = YAML.load_file(module_yaml)

        next unless DeploymentModule.find_by_name(module_info['module_name']).nil?

        modules << DeploymentModule.new(
            name:           module_info['module_name'],
            description:    module_info['module_description'],
            module_path:    module_rb,
            module_version: module_info['module_version'],
        )
      rescue Exception => e
        logger.error(e)
      end
    end

    modules
  end

  def install_parameters
    install_attributes = {}

    (self.attribute_names - %w(id created_at updated_at)).each do |a|
      install_attributes[a.to_sym] = self.read_attribute(a)
    end

    install_attributes
  end

  def self.upload_and_install(module_archive_file)
    deployment_module = DeploymentModule.new(
      module_files: []
    )

    begin
      Zip::File.open(module_archive_file) do |zip_file|
        entry = zip_file.glob('module.yml').first

        if entry
          yml = entry.get_input_stream.read
          module_info = YAML.load(yml)
          module_name = module_info['module_name']

          if module_name
            module_path = File.join(ENV['DEPLOYMENT_MODULE_BASE_DIRECTORY'] || Rails.root.to_s, DeploymentModule.module_directory, "#{SecureRandom.uuid}_#{module_name.downcase}")

            deployment_module.name            = module_info['module_name']
            deployment_module.description     = module_info['module_description']
            deployment_module.module_path     = File.join(module_path, "#{module_name.downcase}.rb")
            deployment_module.module_version  = module_info['module_version']

            deployment_module.default_parameters_applications   = module_info['default_parameters_applications'] || {}
            deployment_module.default_parameters_deployments    = module_info['default_parameters_deployments'] || {}
            deployment_module.default_parameters_environments   = module_info['default_parameters_environments'] || {}
            deployment_module.settings                          = module_info['default_settings'] || {}

            unless DeploymentModule.where('name = ?', module_info['module_name']).any?
              FileUtils::mkdir_p(module_path)
              deployment_module.deploy_files(module_info, zip_file, module_path)
            end
          else
            deployment_module.errors.add(:module_archive_file, 'has a module.yml file containing an invalid or missing module_name')
          end
        else
          deployment_module.errors.add(:module_archive_file, 'does not contain a module.yml file')
        end
      end
    rescue Exception => e
      deployment_module.errors.add(:module_archive_file, 'is invalid or there was an issue installing the Deployment Module. Please notify the administrator.')
      logger.error(e.message)
    end

    deployment_module.remove_module_directory if deployment_module.errors.any?

    deployment_module
  end

  def upload_and_upgrade(module_archive_file)
    begin
      Zip::File.open(module_archive_file) do |zip_file|
        entry = zip_file.glob('module.yml').first

        if entry
          yml = entry.get_input_stream.read
          module_info = YAML.load(yml)
          module_name = module_info['module_name']

          if module_name
            module_path = Pathname.new(self.module_path).dirname

            self.description     = module_info['module_description']
            self.module_path     = File.join(module_path, "#{module_name.downcase}.rb")
            self.module_version  = module_info['module_version']


            #self.remove_module_directory(false)
            self.deploy_files(module_info, zip_file, module_path)
          else
            self.errors.add(:module_archive_file, 'has a module.yml file containing an invalid or missing module_name')
          end
        else
          self.errors.add(:module_archive_file, 'does not contain a module.yml file')
        end
      end
    rescue Exception => e
      self.errors.add(:module_archive_file, 'is invalid or there was an issue upgrading the Deployment Module. Please notify the administrator.')
      logger.error(e.message)
    end

    self
  end

  def self.module_directory
    AppConfig.get(%w(deployment modules_directory), APP_CONFIG) || File.join('vendor', 'deployment_modules')
  end

  def remove_module_directory(remove_directory = true)
    if self.module_files

      self.module_files.each do |file|
        File.delete(file) if File.exist?(file)
      end

      if remove_directory && self.module_path
        module_dir = File.dirname(self.module_path)
        FileUtils.remove_dir(module_dir) if File.exist?(module_dir)
      end
    else
      logger.warn("The module #{self.id} - #{self.name} did not have the module_files attribute set, not attempting to delete its files.")
    end
  end

  def deploy_files(module_info, zip_file, module_path)
    module_name = module_info['module_name']

    valid_module = {
        'module.yml'                  =>  false,
        "#{module_name.downcase}.rb"  =>  false
    }

    zip_file.each do |entry|
      valid_module[entry.to_s] = true if valid_module.keys.include?(entry.to_s)
      module_file_path = File.join(module_path, entry.to_s)

      File.open(module_file_path, 'w') { |file| file.write(entry.get_input_stream.read) }
      self.module_files << module_file_path
    end

    if valid_module.values.include?(false)
      self.errors.add(:module_archive_file, "is missing module file(s): #{(valid_module.select { |k,v| !v }).keys.join(', ')}")
    end
  end
end

app/controllers/admin/deployment_modules_controller.rb
class Admin::DeploymentModulesController < Admin::BaseController
  load_and_authorize_resource

  def index
    @deployment_modules = DeploymentModule.all
    @available_deployment_modules = DeploymentModule.available_modules
  end

  def show
    @deployment_module = DeploymentModule.find(params[:id])
  end

  def edit
    @deployment_module  = DeploymentModule.find(params[:id])

    @parameters_hash = collect_deployment_parameters
  end

  def update
    @deployment_module = DeploymentModule.find(params[:id])

    respond_to do |format|
      if @deployment_module.update_attributes(deployment_module_params)
        format.html { redirect_to session[:user_return_to] ? session[:user_return_to] : admin_deployment_modules_path, notice: "#{t('deployment_modules.updated')} - #{@deployment_module.name}" }
      else
        @parameters_hash = collect_deployment_parameters

        format.html { render action: "edit" }
      end
    end
  end

  def destroy
    @deployment_module = DeploymentModule.find(params[:id]).destroy

    flash[:notice] = "#{t('deployment_modules.deleted')} - #{@deployment_module.name}"

    respond_to do |format|
      format.html { redirect_to admin_deployment_modules_path }
      format.json { head :no_content }
    end
  end

  def upload
    @deployment_module = DeploymentModule.new
  end

  def perform_upload
    respond_to do |format|
      @deployment_module = DeploymentModule.upload_and_install(params[:deployment_module][:module_archive_file].tempfile.path)

      if @deployment_module.errors.none? && @deployment_module.save
        format.html { redirect_to edit_admin_deployment_module_path(@deployment_module), notice: "#{t('deployment_modules.installed')} - #{@deployment_module.name}" }
      else
        format.html { render action: 'upload' }
      end
    end
  end

  def upgrade
    @deployment_module = DeploymentModule.find(params[:id])
  end

  def perform_upgrade
    @deployment_module = DeploymentModule.find(params[:id])

    respond_to do |format|
      if @deployment_module.upload_and_upgrade(params[:deployment_module][:module_archive_file].tempfile.path) && @deployment_module.errors.none? && @deployment_module.save
        format.html { redirect_to edit_admin_deployment_module_path(@deployment_module), notice: "#{t('deployment_modules.upgraded')} - #{@deployment_module.name}" }
      else
        format.html { render action: 'upload' }
      end
    end
  end

  private
  def deployment_module_params
    params.require(:deployment_module).permit(:name, :description, :module_path, :module_version).merge( {
                                                                                                             settings:                          YAML.load(params[:deployment_module][:settings]) || {},
                                                                                                             default_parameters_applications:   YAML.load(params[:deployment_module][:default_parameters_applications]) || {},
                                                                                                             default_parameters_deployments:    YAML.load(params[:deployment_module][:default_parameters_deployments]) || {},
                                                                                                             default_parameters_environments:   YAML.load(params[:deployment_module][:default_parameters_environments]) || {},
                                                                                                         })
  end

  def collect_deployment_parameters
    {
        settings:                         params[:settings]                         || deployment_parameters_to_string(@deployment_module.settings.to_yaml),
        default_parameters_applications:  params[:default_parameters_applications]  || deployment_parameters_to_string(@deployment_module.default_parameters_applications),
        default_parameters_deployments:   params[:default_parameters_deployments]   || deployment_parameters_to_string(@deployment_module.default_parameters_deployments),
        default_parameters_environments:  params[:default_parameters_environments]  || deployment_parameters_to_string(@deployment_module.default_parameters_environments),
    }
  end
end

app/controllers/api/v1/deployment_modules_controller.rb
class API::V1::DeploymentModulesController < ApplicationController
  load_and_authorize_resource
  before_action :set_deployment_module, only: [:show]

  swagger_controller :deployment_modules, 'Deployment Module Management'

  swagger_api :index do
    summary 'Fetches all Deployment Module items'
    notes 'This lists all the Deployment Modules'
    param :header, 'X-User-Email', :string, :required, 'User Email'
    param :header, 'X-User-Token', :string, :required, 'User Token'
  end

  swagger_api :show do
    summary 'Fetches a single Deployment Module item'
    param :header, 'X-User-Email', :string, :required, 'User Email'
    param :header, 'X-User-Token', :string, :required, 'User Token'
    param :path, :id, :integer, :required, 'Deployment Module ID'
  end


  # GET /api/deployment_modules
  def index
    @deployment_modules = DeploymentModule.all
  end

  # GET /api/deployment_modules/1
  def show
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_deployment_module
    @deployment_module = DeploymentModule.find(params[:id])
  end
end

app/helpers/admin/deployment_modules_helper.rb
module Admin::DeploymentModulesHelper
end

app/helpers/api/v1/deployment_modules_helper.rb
module API::V1::DeploymentModulesHelper
end

app/views/admin/deployment_modules/_form.html.erb
    <% if @deployment_module.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@deployment_module.errors.count, "error") %> prohibited this approval group from being saved:</h2>

          <ul>
            <% @deployment_module.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>
    <div class="field">
      <%= f.label :name %><br />
      <%= f.text_field :name, readonly: true, disabled: true %>
    </div>
    <div class="field">
      <%= f.label :settings %><br />
      <%= f.text_area :settings, :value => @parameters_hash[:settings], :autofocus => true %>
    </div>
    <div class="field">
      <%= f.label :default_parameters_applications %><br />
      <%= f.text_area :default_parameters_applications, :value => @parameters_hash[:default_parameters_applications] %>
    </div>
    <div class="field">
      <%= f.label :default_parameters_deployments %><br />
      <%= f.text_area :default_parameters_deployments, :value => @parameters_hash[:default_parameters_deployments] %>
    </div>
    <div class="field">
      <%= f.label :default_parameters_environments %><br />
      <%= f.text_area :default_parameters_environments, :value => @parameters_hash[:default_parameters_environments] %>
    </div>

app/views/admin/deployment_modules/_upload_form.html.erb
<% if deployment_module.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(deployment_module.errors.count, "error") %> prohibited this deployment module from being uploaded!</h2>

      <ul>
        <% deployment_module.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
<% end %>

<div class="field">
  <%= f.label :module_archive_file %><br />
  <%= f.file_field :module_archive_file %>
</div>

app/views/admin/deployment_modules/edit.html.erb
<h1><%= t('general.editing') % @deployment_module.name %></h1>

<%= form_for(@deployment_module, :url => admin_deployment_module_path) do |f| %>
    <%= render 'form', f: f %>

    <div class="actions">
      <%= f.submit t('deployment_modules.update') %>
    </div>
<% end %>
<br />
<br />
<br />
<%= link_to t('general.actions.back'), :back %>

app/views/admin/deployment_modules/index.html.erb
<br />
<div class="panel panel-default">
  <div class="panel-heading">
    <%= t('deployment_modules.deployment_modules') %>
  </div>
  <div class="panel-body">
    <table class='data_table' id="server_groups_table">
      <thead>
      <tr>
        <th><%= t('deployment_modules.name') %></th>
        <th><%= t('deployment_modules.installed') %></th>
        <th><%= t('deployment_modules.module_version') %></th>
        <th><%= t('general.actions.actions') %></th>
      </tr>
      </thead>
      <tbody>
      <% @deployment_modules.each do |deployment_module| %>
          <tr id="deployment_module_<%= deployment_module.id %>">
            <td><%= link_to deployment_module.name, admin_deployment_module_path(deployment_module) %></td>
            <td><%= t('general.boolean_yes') %></td>
            <td><%= deployment_module.module_version %></td>
            <td>
              <%= link_to(t('deployment_modules.upgrade'), upgrade_admin_deployment_module_path(deployment_module)) if can? :upgrade, DeploymentModule %>
              <%= link_to(t('general.actions.edit'), edit_admin_deployment_module_path(deployment_module)) if can? :edit, DeploymentModule %>
              <%= link_to(t('general.actions.delete'), admin_deployment_module_path(deployment_module), :confirm => t('general.are_you_sure'), :method => :delete) if can? :destroy, DeploymentModule %>
            </td>
          </tr>
      <% end %>
      <% @available_deployment_modules.each do |deployment_module| %>
          <tr id="deployment_module_<%= deployment_module.id %>">
            <td><%= deployment_module.name %></td>
            <td><%= t('general.boolean_no') %></td>
            <td><%= deployment_module.module_version %></td>
            <td>
              <%= link_to(t('deployment_modules.install'), admin_deployment_modules_path(deployment_module: deployment_module.install_parameters), method: :post) if can? :create, DeploymentModule %>
            </td>
          </tr>
      <% end %>
      </tbody>
    </table>
  </div>
</div>

<% if can?(:upload, DeploymentModule) and can?(:perform_upload, DeploymentModule) %>
    <span class='actions'>
      <%= link_to t('general.actions.upload'), upload_admin_deployment_modules_path, :id => 'upload_admin_deployment_modules_link' %>
    </span>
<% end %>

app/views/admin/deployment_modules/new.html.erb
<h1><%= t('general.new') % t('deployment_modules.deployment_module') %></h1>

<%= form_for(@deployment_module, :url => admin_deployment_modules_path) do |f| %>
    <%= render 'form', f: f %>

    <div class="actions">
      <%= f.submit t('deployment_modules.create') %>
    </div>
<% end %>
<br />
<br />
<br />
<%= link_to t('general.actions.back'), :back %>

app/views/admin/deployment_modules/show.html.erb
<h1><%= @deployment_module.name.titleize %></h1>
<br />
<div class="panel panel-default">
  <div class="panel-heading"><%= t('deployment_modules.deployment_module_attributes') %></div>

  <table class="table">
    <tr>
      <th><%= t('look_and_feel.account.attributes.name') %></th>
      <th><%= t('look_and_feel.account.attributes.attribute') %></th>
    </tr>
    <tr>
      <td><%= t('deployment_modules.description') %></td>
      <td><%= @deployment_module.description %></td>
    </tr>
    <tr>
      <td><%= t('deployment_modules.module_version') %></td>
      <td><%= @deployment_module.module_version %></td>
    </tr>
    <tr>
      <td><%= t('deployment_modules.settings') %></td>
      <td><%= @deployment_module.settings %></td>
    </tr>
    <tr>
      <td><%= t('deployment_modules.default_parameters_applications') %></td>
      <td><%= @deployment_module.default_parameters_applications %></td>
    </tr>
    <tr>
      <td><%= t('deployment_modules.default_parameters_deployments') %></td>
      <td><%= @deployment_module.default_parameters_deployments %></td>
    </tr>
    <tr>
      <td><%= t('deployment_modules.default_parameters_environments') %></td>
      <td><%= @deployment_module.default_parameters_environments %></td>
    </tr>
    <tr>
      <td><%= t('deployment_modules.module_path') %></td>
      <td><%= @deployment_module.module_path %></td>
    </tr>
  </table>
</div>
<br />
<%= link_to(t('deployment_modules.upgrade'), upgrade_admin_deployment_module_path(@deployment_module)) if can? :upgrade, DeploymentModule %>
<%= link_to(t('general.actions.edit'), edit_admin_deployment_module_path(@deployment_module)) if can? :edit, DeploymentModule %>
<%= link_to t('general.actions.back'), :back %>

app/views/admin/deployment_modules/upgrade.html.erb
<h1><%= t('general.upload') % t('deployment_modules.deployment_module_archive') %></h1>
<%= form_for(@deployment_module, {url: perform_upgrade_admin_deployment_module_path, multipart: true}) do |f| %>
    <div class="alert-warning">
      <strong><%= t('general.alerts.warning') %>!</strong> <%= t('deployment_modules.alerts.restart_background_process') %>
    </div>

    <%= render 'upload_form', deployment_module: @deployment_module, f: f %>

    <div class="actions">
      <%= f.submit "#{t('deployment_modules.upgrade')} #{t('deployment_modules.deployment_module')}" %>
    </div>
<% end %>

app/views/admin/deployment_modules/upload.html.erb
<h1><%= t('general.upload') % t('deployment_modules.deployment_module_archive') %></h1>
<%= form_for(@deployment_module, {url: perform_upload_admin_deployment_modules_path, multipart: true}) do |f| %>
    <%= render 'upload_form', deployment_module: @deployment_module, f: f %>

    <div class="actions">
      <%= f.submit t('deployment_modules.upload') %>
    </div>
<% end %>